### ISSUE TITLE
customize transcoding resolution quality

### ISSUE THREAD

**Issue by Siyuan-Zheng** [jellyfin/Swiftfin#625] opened 2022-11-03 08:05 UTC
i use nat tool like ZeroTier to help me connect the library when i outside, but the network operator offers limited upload bandwidth, when i play 4k video the server is push direct stream and not use transcoding to low resolution or low bit rate, which hard to play original frame rate video because the low upload bandwidth

is there has some way to let server push video stream with transcoding?
if can't, wish can add an resolution and bit rate select in setting, just like the player web version

**Comment by LePips** [comment] 2022-11-03 19:18
Duplicate of https://github.com/jellyfin/Swiftfin/issues/184

**Comment by LePips** [comment] 2022-11-03 19:18
Duplicate of https://github.com/jellyfin/Swiftfin/issues/184

**Closed by LePips** 2022-11-03 19:18 UTC
Labels: enhancement
