### ISSUE TITLE
Sort order not saved

### ISSUE THREAD

**Issue by zsh-rc** [jellyfin/Swiftfin#574] opened 2022-09-11 20:29 UTC
### Describe the bug

Go to ``Media > Shows``
Click on ``Sort`` by random
Go back to homepage
Go back to ``Shows``
Sort by random isn't a saved state

**Great job on the update**

### Application version

1.0.0(77)

### Where did you install the app from?

TestFlight

### Device information

iPhone 10

### OS version

15.6.1

### Jellyfin server version

10.8.4

**Comment by LePips** [comment] 2022-09-11 20:47
Duplicate of https://github.com/jellyfin/Swiftfin/issues/441.

**Closed** 2022-09-11 20:48 UTC
Labels: bug, duplicate
