### ISSUE TITLE
Show extras not showing up

### ISSUE THREAD

**Issue by samuraimarv** [jellyfin/Swiftfin#666] opened 2023-01-02 04:06 UTC
### Describe the bug

1. Guide says to name additional things in a folder called "extras" or something like it: https://jellyfin.org/docs/general/server/media/shows/
2. Jellyfin picks this up and displays them on the Shows page as "Special Features". This works in the web client and iOS Jellyfin client.
3. On the tvOS and iOS Swiftfin clients when going to series page there is no "Special Features" section and no way to view the extra footage.

### Application version

tvOS 1.0.0(84), iOS 1.0.0(79)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K (2nd generation), iPhone 14 Pro Max

### OS version

tvOS 16.2, iOS 16.2

### Jellyfin server version

10.8.8

**Comment by LePips** [comment] 2023-01-02 04:50
Duplicate of https://github.com/jellyfin/Swiftfin/issues/453

**Closed by LePips** 2023-01-02 04:50 UTC
Labels: bug

**Comment by RaptorCentauri** [comment] 2023-02-27 17:09
Is there a reason this was closed and marked as duplicate? This question is about the display of special features for TV shows. The linked duplicate is about special features for movies.

**Comment by ZippoD** [comment] 2023-11-27 11:37
Same issue on Android TV
