### ISSUE TITLE
Multi-part movies only show the first part

### ISSUE THREAD

**Issue by zhen-huan-hu** [jellyfin/Swiftfin#858] opened 2023-09-21 19:01 UTC
### Describe the bug

1. For movies split into multiple parts, such as "film-part1.mkv", "film-part2.mkv", the 2nd and later parts are shown under "other parts" in Jellyfin web interface. However, they are not shown anywhere in Swiftfin and thus not accessible.

### Application version

1.0.1

### Where did you install the app from?

App Store

### Device information

iPhone 13

### OS version

iOS 17.0

### Jellyfin server version

10.8.10

**Comment by LePips** [comment] 2023-09-29 04:38
Duplicate of #798

**Closed by LePips** 2023-09-29 04:38 UTC
Labels: duplicate
