### ISSUE TITLE
tvOS App not refreshing library

### ISSUE THREAD

**Issue by movh** [jellyfin/Swiftfin#1330] opened 2024-11-27 13:15 UTC
### Describe the bug

The library will not get updated. A normal power off and on on the Apple TV does not help. Only hard-quitting and reopening the app will refresh the library.

### Application version

1.0.1(70)

### Where did you install the app from?

App Store

### Device information

Apple TV 4K

### OS version

18.1

### Jellyfin server version

10.10.0

**Comment by JPKribs** [comment] 2024-11-27 16:27
This is a duplicate of https://github.com/jellyfin/Swiftfin/issues/784.

**Closed** 2024-11-27 16:28 UTC
Labels: bug
