### ISSUE TITLE
Home bar not automatically hiding

### ISSUE THREAD

**Issue by hotsno** [jellyfin/Swiftfin#239] opened 2021-11-30 04:31 UTC
### Describe the bug

1. Play any video
2. Don't touch screen
2. Home bar never hides

![46147770-1F17-46FA-BAE6-9BF952C6E007](https://user-images.githubusercontent.com/71658949/143986011-da687f1c-23a5-4bc3-b432-3bc20e4d20bd.PNG)

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPhone 13

### OS version

iOS 15.0.2

### Jellyfin server version

10.7.7

**Comment by PangMo5** [comment] 2021-11-30 04:42
Duplicate of #188

**Comment by LePips** [comment] 2021-12-31 14:55
Fixed in (67)

**Closed** 2021-12-31 14:57 UTC
Labels: bug, duplicate
