### ISSUE TITLE
Be able to see my music collection

### ISSUE THREAD

**Issue by avanmd** [jellyfin/Swiftfin#839] opened 2023-09-12 14:48 UTC
**Describe the feature you'd like**

**Additional context**
<!-- Add any other context or screenshots about the feature request here. --

**Comment by thornbill** [comment] 2023-09-12 15:03
No description and a duplicate of https://github.com/jellyfin/Swiftfin/issues/721 and a slew of others

**Closed** 2023-09-12 15:04 UTC
Labels: duplicate
