### ISSUE TITLE
Player is off center on iOS 16

### ISSUE THREAD

**Issue by chnaski** [jellyfin/Swiftfin#590] opened 2022-09-19 02:14 UTC
### Describe the bug

Player is off center on iOS 16 and notch won't disappear
![IMG_6954](https://user-images.githubusercontent.com/39658827/190939751-bea63de6-d83d-477a-bde9-2842ecfdd3fa.PNG)

### Application version

78

### Where did you install the app from?

TestFlight

### Device information

X

### OS version

16

### Jellyfin server version

10.8.4

**Comment by laodiaoyadashu** [comment] 2022-09-23 08:33
<img width="90" alt="image" src="https://user-images.githubusercontent.com/47166052/191921759-4271b623-9a2f-47d7-91f0-46360326e03c.png"> You can try clicking on the location of the screenshot.

**Comment by LePips** [comment] 2022-09-23 15:17
Aspect fill isn't the issue, the issue is the top bar being offset due to there being a rogue navigation bar from the system. This will most likely be fixed by just compiling with the iOS 16 SDK in the next release.

**Closed** 2023-04-20 15:34 UTC
Labels: bug
