### ISSUE TITLE
Deleting movie from Jellyfin gives "no results" in Swiftfin

### ISSUE THREAD

**Issue by johncadengo** [jellyfin/Swiftfin#647] opened 2022-12-19 03:59 UTC
### Describe the bug

When I deleted a movie from Jellyfin and went to my Swiftfin library to see the updates movie list, it returns "no results."

Looks like a bug in Swiftfin. Jellyfin web interface works just fine. In addition, I can't do any of the following:

- Can't refresh the movies tab or collection
- Can't log out of my jellyfin instance and log back in
- Can't access it via the "media" tab and then going to "movies" under there
- Can't access any of the movies in my movies tab under search -- since it appears to be searching whatever data structure is on the client side rather than making an api call to the server

Currently only "TV Shows" collection works for me.

Any ideas on how to fix? In attempting to reinstall swiftfin, I accidentally removed myself from the beta tester list (Testflight UX is not intuitive) so now I don't have a way to update my app either.

### Application version

1.0.0(84)

### Where did you install the app from?

TestFlight

### Device information

Apple TV 4k

### OS version

TvOS

### Jellyfin server version

10.8.7

**Comment by LePips** [comment] 2022-12-19 21:42
Duplicate of https://github.com/jellyfin/Swiftfin/issues/621

**Closed by LePips** 2022-12-19 21:42 UTC
Labels: bug
