### ISSUE TITLE
tvOS top nav bar not hiding during playback

### ISSUE THREAD

**Issue by hendrik1120** [jellyfin/Swiftfin#252] opened 2022-01-01 14:52 UTC
### Describe the bug

After selecting any Movie, the top navigation bar (Home, all media, settings) simply stays on top of the content. It's also not possible to get back to the Home Screen of the App because pressing MENU on the remote closes the app instantly.
It's just very distracting while watching content.

### Application version

1.0.0(66)

### Where did you install the app from?

TestFlight

### Device information

AppleTV 4k

### OS version

tvOS 15.2

### Jellyfin server version

10.7.7

**Comment by LePips** [comment] 2022-01-01 17:34
This was supposed to be fixed in (66), please update to (67) and report if the problem is still there.

**Comment by hendrik1120** [comment] 2022-01-01 18:17
Yeah, the only problem is that build 67 is not showing in my TestFlight app on tvOS. I have tried pretty much everything but even after several rejoins with the link und uninstalls of TestFlight and the app it is still only showing the old (67) build. Funny thing is that macOS and iOS show the new version as usual.
Is my TestFlight just bugged or did the build didn't push to tvOS correctly?

**Comment by acvigue** [comment] 2022-01-01 20:11
tvOS testflight is under review for some reason. I'll give Apple a couple days before trying to push it out again

**Comment by LePips** [comment] 2022-01-01 20:12
Thanks Aiden, sorry for putting you (@hendrik1120) through the trouble of uninstalling, un/re-joining and such. The tab bar should be hidden however, as that was a fix in a PR that I can't remember.

**Comment by hendrik1120** [comment] 2022-01-02 01:25
No problem, as soon as I can get my hands on version 67 I'll let you know if it was fixed already and close the issue.

**Comment by acvigue** [comment] 2022-01-02 18:47
> Thanks Aiden, sorry for putting you (@hendrik1120) through the trouble of uninstalling, un/re-joining and such. The tab bar should be hidden however, as that was a fix in a PR that I can't remember.

no prob. i've been so busy with IRL stuff it's hard to even log in but if you ever need to urgently get me to push something out or have me try to debug etc, just email me or something; i think you have push rights now, so feel free to merge prs if need be.

**Comment by LePips** [comment] 2022-01-06 06:11
As I tagged this for my video player refactor, I found the issue for this and can be closed from view re-designing

**Closed** 2022-01-07 14:47 UTC
Labels: bug
