### ISSUE TITLE
tvOS - Bug/enhancement - Language menu

### ISSUE THREAD

**Issue by Piermaria** [jellyfin/Swiftfin#1332] opened 2024-11-27 15:25 UTC
**Describe the feature you'd like**

Hello,

When playing a movie, the subtitles/audio language menu is difficult to make appear, this needs just a tap on the remote but often is not registered by the remote, furthermore on Siri Remotes is not possible to tap. Eventually the user is able to open the menu but this results in mild frustration.

It would be easier if a button was placed next to the Subs on/off button above the timeline bar to open the language menu.

Thanks

**Additional context**

**Comment by LePips** [comment] 2024-11-27 17:03
Considering a duplicate of #914, but will be fixed in #1203

**Closed by LePips** 2024-11-27 17:03 UTC
Labels: enhancement
