### ISSUE TITLE
[FR] Music support

### ISSUE THREAD

**Issue by el-tiuri** [jellyfin/Swiftfin#110] opened 2021-07-16 08:41 UTC
I’d love to see support for music being added. Is that planned, or is this only supposed to be a video player?

**Comment by acvigue** [comment] 2021-07-16 15:06
Intended for video, a great app for Music is FinAmp :)

**Comment by charleypeng** [comment] 2021-07-20 14:25
same here,  this native app is great. I would like to help translate into Chinese.   I was intended to develop my own by using Xamarin, but now, it seems to be unnecessary.

**Comment by PangMo5** [comment] 2021-07-20 23:24
> same here, this native app is great. I would like to help translate into Chinese. I was intended to develop my own by using Xamarin, but now, it seems to be unnecessary.

Thank you for your interest in Swiftfin.
It's not fully implemented at the moment, but you can participate in translation through Weblate.

https://translate.jellyfin.org/projects/swiftfin/swiftfin/

**Comment by charleypeng** [comment] 2021-07-21 04:56
> > same here, this native app is great. I would like to help translate into Chinese. I was intended to develop my own by using Xamarin, but now, it seems to be unnecessary.
> 
> Thank you for your interest in Swiftfin.
> It's not fully implemented at the moment, but you can participate in translation with Weblate.
> 
> https://translate.jellyfin.org/projects/swiftfin/swiftfin/

I've translated it, still have some inaccurate problems and I think it can be fixed when the app is out and using the translation.

**Comment by charleypeng** [comment] 2021-07-22 02:28
> > same here, this native app is great. I would like to help translate into Chinese. I was intended to develop my own by using Xamarin, but now, it seems to be unnecessary.
> 
> Thank you for your interest in Swiftfin.
> It's not fully implemented at the moment, but you can participate in translation with Weblate.
> 
> https://translate.jellyfin.org/projects/swiftfin/swiftfin/

so, i do not know where did all the translation gone? ^^||

**Comment by PangMo5** [comment] 2021-07-22 03:09
> so, i do not know where did all the translation gone? ^^||

The translation-related structure has been modified and the existing translation has been initialized.
But it's remembered by Weblate.
You can check the previous translation from the right panel.

![스크린샷 2021-07-22 오후 12 08 10](https://user-images.githubusercontent.com/16532526/126584793-544f3662-7da1-4e96-b8d4-cab72c6ef641.png)

**Comment by acvigue** [comment] 2021-07-31 11:53
> There are too many comments unrelated to this issue.
To continue, please talk to Jellyfin discord or matrix.

I agree, I will mark this issue closed as an alternative app has been suggested for the time being.

**Closed by acvigue** 2021-07-31 11:53 UTC
