### ISSUE TITLE
Swiftfin iOS ChromeCast Support

### ISSUE THREAD

**Issue by trickbaze** [jellyfin/Swiftfin#813] opened 2023-08-06 15:53 UTC
### Describe the bug

Is there anyway to use ChromeCast support in Swiftfin? Or did i need get applied for the Testflight version?

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iPhone 14 Pro

### OS version

iOS 17 (beta)

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment] 2023-08-06 16:23
Duplicate of #271

**Closed by thornbill** 2023-08-06 16:23 UTC
Labels: bug
