### ISSUE TITLE
Next/Previous controls and seek slider broken

### ISSUE THREAD

**Issue by ishanjain28** [jellyfin/Swiftfin#414] opened 2022-04-18 16:48 UTC
### Describe the bug

Play a Movie or a TV Show.

1. Pressing `<< (15)` or `>> (15)` should seek it +/- 15 seconds. Instead, It goes to previous/next episode in the series or just jumps out of the player for a movie. i.e., It's acting as a Previous/Next button.
2. The seek slider is stuck at 0:00. Sliding it manually closes the player.

### Application version

1.0.0(74)

### Where did you install the app from?

TestFlight

### Device information

iPad Air 3

### OS version

15.4.1

### Jellyfin server version

jellyfin-server-git 10.8.0.alpha5.r361.gcf47ee6261-1 jellyfin-web-git 10.8.0.alpha5.r361.gcf47ee6261-1

**Comment by LePips** [comment] 2022-04-18 18:24
Is the stream you're experiencing this on transcoded or direct play?

**Comment by ishanjain28** [comment] 2022-04-18 19:06
@LePips direct play

**Comment by LePips** [comment] 2022-04-18 19:32
I am unable to replicate. For some more information, are you using the normal or compact overlay?

**Comment by ishanjain28** [comment] 2022-04-20 03:30
@LePips I removed and reinstalled the app and still have this problem. 

I am using the normal overlay but I can also replicate this problem with compact overlay.

**Comment by LePips** [comment] 2022-04-20 06:41
I will have to test with an iPad then. Are you sure that you're tapping the buttons in the middle/on the bottom left, and not in the top right?

**Comment by ishanjain28** [comment] 2022-04-20 07:29
@LePips Yes. I am tapping on the buttons in the middle in normal layout and the buttons in bottom-left corner in compact layout. I'd be happy to share a video capture if that helps?

**Comment by ishanjain28** [comment] 2022-04-20 07:30
I am not sure about the current revision of swiftfin but until the lasts release, The Left/Right arrow buttons in top right corner don't do anything.

**Comment by LePips** [comment] 2022-04-20 13:42
That would help, thank you

**Comment by aidzer0** [comment] 2022-06-25 21:04
I can confirm this is happening on Apple TV as well. Latest tvOS (15.5.1), latest Swiftfin (beta 74) and Jellyfin (10.7.7).

in my case, it only happens on random media, a mixture of movies and tbh shows. Some show the play time and ff and rewind work fine, others don’t.

Everything is forced in direct play, but it also happens if media is being transcoded.

**Comment by ishanjain28** [comment] 2022-06-26 17:13
> I have “mitigated” this issue by scrubbing through Jellyfin web or mobile app, then resuming on Swiftfin, after resuming the time stamp still shows 00:00 on Swiftfin.

This is also I had worked around this issue.

But strangely enough, This problem sorted itself out on it's own roughly a month after my last reply here. My current installation is on, `1.0.0(75)` and I don't have any of the issues I had shared in this issue. I also don't see this release in Github so I am not exactly sure when did this happen.

**Comment by aidzer0** [comment] 2022-06-26 17:16
I misspoke, I have beta 75 installed. I’ll see if removing and re-installing will help. Thanks!

**Comment by LePips** [comment] 2022-06-26 17:58
Sorry, the releases most likely won't be up to date with the TestFlight just because we have to do it manually and only really bother with it when people ask.

For this issue, I have been experiencing it only with one movie of mine. Frankly, I can only point to VLCKit as it handles all video playback. This may be handled better when I start moving to mpv.

**Comment by aidzer0** [comment] 2022-06-26 18:02
> Sorry, the releases most likely won't be up to date with the TestFlight just because we have to do it manually and only really bother with it when people ask.
> 
> For this issue, I have been experiencing it only with one movie of mine. Frankly, I can only point to VLCKit as it handles all video playback. This may be handled better when I start moving to mpv.

Gotcha, no worries, thanks! I also updated Jellyfin to 10.8.0 and the black screen issue went away so that’s good. (Separate issue that’s open on GitHub).

**Comment by sebirdman** [comment] 2022-07-22 02:37
I'm seeing this as well. Here's my anecdote:

I've got two an Apple TV devices: a HD and a 4K. 

On my 4K Swiftfin is fantastic. 

On my HD, I've got this bug on every single file, and the video playback is pretty choppy. 

Unfortunately, the HD is on wifi and not hardwired, so it's not a perfectly similar setup. I'll have to see if I swap the units if the HD works better. And report back.

**Comment by JonathanVusich** [comment] 2022-07-26 15:32
I am seeing this issue as well on my Apple TV (2021 edition). The app is continually improving (which is great!) but seeking has been broken for months.

**Comment by aidzer0** [comment] 2022-07-26 15:39
> I'm seeing this as well. Here's my anecdote:
> 
> I've got two an Apple TV devices: a HD and a 4K.
> 
> On my 4K Swiftfin is fantastic.
> 
> On my HD, I've got this bug on every single file, and the video playback is pretty choppy.
> 
> Unfortunately, the HD is on wifi and not hardwired, so it's not a perfectly similar setup. I'll have to see if I swap the units if the HD works better. And report back.




> I am seeing this issue as well on my Apple TV (2021 edition). The app is continually improving (which is great!) but seeking has been broken for months.

I have been able to mitigate the issue by using the “force direct play” under experimental settings, the only issue is x265 media does not like direct playback, assuming since the 1080p appleTV doesn’t support x265 or something. 
We will just need to wait for further updates.
Another work around is to airplay from your phone or iPad. Sometimes I do that too. That way watch progression is logged.

**Closed** 2023-04-20 15:34 UTC
Labels: bug
