### ISSUE TITLE
Hide home bar on iOS when viewing videos.

### ISSUE THREAD

**Issue by ZachT112** [jellyfin/Swiftfin#915] opened 2023-11-16 04:15 UTC
**Describe the feature you'd like**

Pretty self explanatory. Home bar should hide during video playback instead of remaining on the screen like on YouTube and other video players.

Should be relatively simple with some sort of override of "prefersHomeIndicatorAutoHidden" returning true when in the video player mode.

**Comment by thornbill** [comment] 2023-11-16 04:25
Duplicate of #582

**Closed** 2023-11-16 04:25 UTC
Labels: enhancement
