### ISSUE TITLE
The navigation bar does not disappear when you play media

### ISSUE THREAD

**Issue by karolpeszek** [jellyfin/Swiftfin#815] opened 2023-08-06 23:12 UTC
### Describe the bug

Play any movie either with native or non-native player. The navigation bar stays on the screen while media playback.
![IMG_0256](https://github.com/jellyfin/Swiftfin/assets/46539811/ec2dcab5-7ce3-4254-b49f-a57f5f806358)

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPad Pro 12.9” (6th gen.)

### OS version

iPadOS 16.6

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment] 2023-08-07 00:28
Duplicate of #582. Should be fixed in the next release.

**Closed by thornbill** 2023-08-07 00:28 UTC
Labels: bug
