### ISSUE TITLE
Odd scrolling behaviour on Home Screen

### ISSUE THREAD

**Issue by LeviSnoot** [jellyfin/SwiftFin#81] opened 2021-06-21 17:54 UTC
Build 50
https://user-images.githubusercontent.com/13402525/122806278-6e425600-d2ca-11eb-8e5a-97f30310923d.MOV

**Comment by PangMo5** [comment] 2021-06-21 19:04
I'll check it

**Comment by classicjazz** [comment] 2021-06-21 21:14
I can confirm that this is an issue on my iPhone 12 Max. 

To reproduce, 
1. on the home screen, scroll all the way down
2. scroll all the way up until it hits the top and bounces 

I don't see this behavior on my M1 iPad Pro, however.

**Comment by acvigue** [comment] 2021-06-22 02:30
iOS v?
15 has known issues with the home screen.

**Comment by PangMo5** [comment] 2021-06-22 02:37
This may be a problem with the combination of Spacer and iOS 15(Maybe not), LazyVStack, and NavigationView.

Currently, I think we're using Spacer to set the spacing between views.
Maybe this is the same as using Color.clear
This is not Apple's intended method and may have unintended side effects.
Therefore, it would be better to use .padding for spacing between views.

If replace that part with padding, it works normally.

**Comment by PangMo5** [comment] 2021-06-22 02:38
Of course, this may be resolved in beta later 😋

**Comment by acvigue** [comment] 2021-06-22 02:39
> If replace that part with padding, it works normally.

would you be willing to throw up a quick PR with the changes?

**Comment by PangMo5** [comment] 2021-06-22 02:40
> > If replace that part with padding, it works normally.
> 
> would you be willing to throw up a quick PR with the changes?

Yes, the corresponding part has been modified, 
but I can see other problems on the home screen, 
so I will upload them after I correct them.

**Comment by acvigue** [comment] 2021-06-22 03:48
reopening until proven fixed.

**Comment by LeviSnoot** [comment] 2021-06-22 09:28
> 
> 
> iOS v?
> 15 has known issues with the home screen.

v14.6

**Comment by classicjazz** [comment] 2021-06-22 13:02
I updated my comments to reflect 14.6 on both devices.

**Comment by Hukuma1** [comment] 2021-06-22 16:59
iOS v14.3 same thing. Also has weird binding/bounce if you flip orientation into landscape mode.

**Comment by krutburken** [comment] 2021-06-22 18:35
Can also confirm this on 14.6 (12 mini)

**Comment by acvigue** [comment] 2021-06-23 19:23
may be fixed in 51

**Comment by acvigue** [comment] 2021-06-25 01:20
please lmk if this still occurs in 53.

**Comment by classicjazz** [comment] 2021-06-25 01:28
Definitely improved on the iPhone 12 Max running 14.6. I don't see it screen redraw (fluttering) at all in either landscape or portrait mode.

Almost fixed on the M1 iPad Pro running 14.6. No artifacts in landscape mode. But there are still screen redraw (fluttering) issues in portrait mode there.

**Comment by PangMo5** [comment] 2021-06-25 02:31
> Definitely improved on the iPhone 12 Max running 14.6. I don't see it screen redraw (fluttering) at all in either landscape or portrait mode.
> 
> Almost fixed on the M1 iPad Pro running 14.6. No artifacts in landscape mode. But there are still screen redraw (fluttering) issues in portrait mode there.

Can you upload the example video that working on the M1 iPad Pro?

**Comment by LeviSnoot** [comment] 2021-06-25 13:51
> 
> 
> please lmk if this still occurs in 53.

Fixed for me in build 53

**Comment by Hukuma1** [comment] 2021-06-25 16:09
Ditto. Fixed on my iPhone 11 Pro. Thanks!

**Comment by acvigue** [comment] 2021-06-25 17:55
np. closing.

**Closed by acvigue** 2021-06-25 17:55 UTC
Labels: bug, can't reproduce

**Comment by classicjazz** [comment] 2021-06-25 21:06
> > Definitely improved on the iPhone 12 Max running 14.6. I don't see it screen redraw (fluttering) at all in either landscape or portrait mode.
> > Almost fixed on the M1 iPad Pro running 14.6. No artifacts in landscape mode. But there are still screen redraw (fluttering) issues in portrait mode there.
> 
> Can you upload the example video that working on the M1 iPad Pro?

Here is a link to a video of the flicker when in portrait mode, but not landscape: https://drive.google.com/file/d/1DStUV2lE1eocFzddnZ7GzuuRuo0jmM2N/view

**Comment by PangMo5** [comment] 2021-06-25 21:47
> Here is a link to a video of the flicker when in portrait mode, but not landscape: https://drive.google.com/file/d/1DStUV2lE1eocFzddnZ7GzuuRuo0jmM2N/view
> 
> 
> 
> To replicate, scroll up until it bounces. Then the flicker / screen redraw issue occurs on the M1 iPad running 14.6.

cant access to link

**Comment by classicjazz** [comment] 2021-06-27 16:15
I regenerated the shared link: https://drive.google.com/file/d/1DStUV2lE1eocFzddnZ7GzuuRuo0jmM2N/view?usp=sharing

Hopefully this works for you.
