### ISSUE TITLE
No movies in the media library

### ISSUE THREAD

**Issue by AzuMiWanHua** [jellyfin/Swiftfin#702] opened 2023-02-17 20:17 UTC
No movies are displayed in the media library, only searchable
![IMG_1130](https://user-images.githubusercontent.com/87432333/219784624-5dc871a5-4634-4a82-9f64-3690ae510310.PNG)
![IMG_1131](https://user-images.githubusercontent.com/87432333/219784632-e3add630-f916-414f-af21-e4726b338ff5.PNG)
![IMG_1132](https://user-images.githubusercontent.com/87432333/219784636-8a474553-5372-45f5-8549-33c9e7cb1296.PNG)
![IMG_1133](https://user-images.githubusercontent.com/87432333/219784638-4b8c5067-58e8-4ff1-8fd9-d8c90cb6d81b.PNG)
But the favorites are displayed normally
![IMG_1134](https://user-images.githubusercontent.com/87432333/219785520-f8385352-62db-4299-9461-e050c2dbc105.PNG)

Application version
latest version

Where did you install the app from?
App Store

Device information
iPad Pro 2021 11 inch

OS version
16.3.1

Jellyfin server version
10.8.9

**Comment by dathbe** [comment] 2023-02-27 20:47
I'm seeing this too, though it's intermittent.  I haven't found any patterns on when it happens.  Sometimes I'm unable to even search for movies even though they are clearly showing up in my other clients (web, Roku).

**Comment by dathbe** [comment] 2023-02-27 21:14
Update, duplicate of https://github.com/jellyfin/Swiftfin/issues/621

**Closed** 2023-02-27 21:48 UTC
