### ISSUE TITLE
Audio out of sync over Airplay.

### ISSUE THREAD

**Issue by jkbnk** [jellyfin/Swiftfin#701] opened 2023-02-16 07:05 UTC
### Describe the bug

0. Setup - Apple TV connected to Hisense TV and Airplay enabled Airport Express gen. 1 (all having latest stable firmware/OS). Both Hisense TV and Airport Express are connected via optical to Rotel DAC. Airplay protocol creates an audio buffer delayed by 2000 ms (might differ in some instances), but automatically syncs the tracks on playback.
1. Simply playing any video over Airplay results in delayed audio by few 100s of ms, maybe a second.
2. Routing audio from Apple TV via HDMI to Hisense TV and optical to DAC results in correct sync.
3. I get the same behaviour with VLC on macOS playing via Airplay to any destination. Other players (QuickTime, browser players, etc., ...) sync correctly. I fix this by manually advancing audio track by 2000 ms.
4. I suspect that since Jellyfish uses VLCkit, it doesn't get the information about this discrepancy.

### Application version

1.0.0(84)

### Where did you install the app from?

App Store

### Device information

Apple TV (2021)

### OS version

tvOS 16.3.2

### Jellyfin server version

10.8.9

**Comment by LePips** [comment] 2023-02-17 02:41
Related and marking as duplicate of #420

**Closed by LePips** 2023-02-17 02:41 UTC
Labels: bug
