### ISSUE TITLE
tvOS : Synchronization does not work

### ISSUE THREAD

**Issue by thehuyphan** [jellyfin/Swiftfin#754] opened 2023-04-23 01:56 UTC
### Describe the bug

1. Play a movie
2. Stop and go back to the dashboard.
3. For example, on the dashboard , it is indicated that there is still 1 hour left.
4. Continue the movie on another device
5. On the dashboard of swiftfin on tvOS, it always indicates 1h, the status are not sync

I noticed the same thing for the status seen, not seen.
On iOS, you can force the refresh by dragging the screen down. Impossible to do on tvOS.
I have to kill app on tvOS every time

### Application version

1.0.1(700

### Where did you install the app from?

App Store

### Device information

APPLE TV 4K, lastest version

### OS version

tvOS 16.4.1 (20L498)

### Jellyfin server version

10.8.9

**Comment by LePips** [comment] 2023-04-23 02:01
Duplicate of: #619 (refresh)

**Closed by LePips** 2023-04-23 02:01 UTC
Labels: bug
