### ISSUE TITLE
Posters have no margins

### ISSUE THREAD

**Issue by eximo84** [jellyfin/Swiftfin#571] opened 2022-09-11 07:30 UTC
Latest test flight build on iPhone. Under the media tab if i open any folder (shows, movies) the poster view is all squished and the posters have no margins.

**Comment by LePips** [comment] 2022-09-11 15:48
Duplicate of https://github.com/jellyfin/Swiftfin/issues/557.

**Closed** 2022-09-11 15:48 UTC
Labels: bug, duplicate
