### ISSUE TITLE
ipad pro 12.9 swipe button is not hidden during playback

### ISSUE THREAD

**Issue by ishanjain28** [jellyfin/Swiftfin#626] opened 2022-11-09 12:53 UTC
### Describe the bug

On iPad Pro 12.9 or other ipads that don't have home button, Do the following.

1. Open swiftfin
2. Play anything. 

The swipe button at the bottom does not go away during play back. It does disappear during playback in other apps like vlc, infuse, jellyfin, netflix and others.

ipad pro 12.9 has a bloom effect which is quite noticeable at higher brightness. In swiftfin, That button stays on and there is some bloom around it which is quite distracting. 

Please consider hiding that during playback.

### Application version

1.0.0(78)

### Where did you install the app from?

TestFlight

### Device information

iPad Pro M1 12.9

### OS version

ipados 16.1

### Jellyfin server version

10.8

**Comment by LePips** [comment] 2022-11-09 14:03
Duplicate of #528

**Closed by LePips** 2022-11-09 14:03 UTC
Labels: bug
