### ISSUE TITLE
Swipe (go home) gesture is permanently on display whilst watching media

### ISSUE THREAD

**Issue by Jit-litass** [jellyfin/Swiftfin#749] opened 2023-04-16 06:32 UTC
Hi all,
When watching films the swipe home gesture button (IOS iPhone X and above) the bar stays on whilst watching.
Is there a way this can be fixed? 
so that after 5 seconds it disappears like other apps do?
![IMG_0700](https://user-images.githubusercontent.com/130890118/232277094-d175c8d7-f357-4edf-aa37-63d6449b216d.jpeg)

**Comment by thornbill** [comment] 2023-04-16 16:28
Please search existing issues before creating a new one. This is a duplicate of #582.

**Closed** 2023-04-16 16:29 UTC
Labels: duplicate
