### ISSUE TITLE
Play Music Fullscreen on Swiftfin Apple TV

### ISSUE THREAD

**Issue by QuirkyBongo** [jellyfin/Swiftfin#960] opened 2024-01-28 16:50 UTC
**Describe the feature you'd like**
The ability to play music from your Jellyfin library directly on the Apple TV.

**Additional context**
Looks similar to what Apple Music Looks like, where the backdrop uses colors from the album art to form some gradient or blows up the image, blurs it and rotates it as the backdrop and has the album art in the center of the screen, with the song name and artist underneath that: ![Apple Music Now Playing](https://images.macrumors.com/t/WyI_WSdJ95Yms0bI9oneiF3KJCw=/1600x/article-new/2021/11/apple-music-lg-tv.jpg)

**Comment by LePips** [comment] 2024-01-30 20:59
Duplicate of so many, please search "music" under closed issues.

**Closed by LePips** 2024-01-30 20:59 UTC
Labels: enhancement
