### ISSUE TITLE
Headphones can’t pause video

### ISSUE THREAD

**Issue by Prolons** [jellyfin/Swiftfin#657] opened 2022-12-30 16:45 UTC
### Describe the bug

While watching video on Swiftfin, Bluetooth headphones are not able to pause the video. This occurs for me with Sony headphones and with AirPods. I’ve tried on iPadOS and tvOS. 

On iPadOS when I press pause on the headphones nothing happens. 

On tvOS when I press pause the audio mutes but the video continues. Double tapping on the AirPods a second time does nothing. The only way to get the audio back is to pause and unpause from the remote.

### Application version

1.0.0 (79)

### Where did you install the app from?

TestFlight

### Device information

iPad Pro (11-inch) (3rd generation)

### OS version

iPadOS 16.2

### Jellyfin server version

10.8.8

**Comment by LePips** [comment] 2022-12-30 17:07
Duplicate of https://github.com/jellyfin/Swiftfin/issues/565

**Closed by LePips** 2022-12-30 17:07 UTC
Labels: bug
