### ISSUE TITLE
ipadOS - No ellipsis on top row

### ISSUE THREAD

**Issue by MrTimscampi** [jellyfin/Swiftfin#454] opened 2022-06-05 00:04 UTC
### Describe the bug

1. Add content with very long titles
2. Open Swiftfin on an iPad
3. The first row of featured content will have very wide cards due to non-ellipsized titles, breaking the layout a bit

### Application version

Current TestFlight as of June 5th, 2022

### Where did you install the app from?

TestFlight

### Device information

iPad Air 2022

### OS version

15.5

### Jellyfin server version

10.7.7

**Comment by LePips** [comment] 2022-06-05 00:46
Duplicate of https://github.com/jellyfin/Swiftfin/issues/418, but will soon no longer be an issue with work I'm doing.

**Closed** 2022-06-05 00:46 UTC
Labels: bug
