### ISSUE TITLE
No movies and m4v not playing

### ISSUE THREAD

**Issue by rozenrod** [jellyfin/Swiftfin#664] opened 2023-01-01 22:32 UTC
### Describe the bug

1. Files are not searched on the main page and in the movies folder. Even if I write the name of the movie in the search, the application will not find it.
2. m4v files won't play, I press play but nothing happens. Can you help me with this?

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPad 10.2 2021

### OS version

iPadOS 16.3

### Jellyfin server version

10.8.8

**Comment by erikgk** [comment] 2023-01-02 07:41
I have the same issue I think:
1. Shows are shown
2. Movies are “No results”
3. Last played movie is shown & I can play that one 
4. sort of a workaround: start the movie using the web interface, then refresh the app to continue viewing it on the app
5. The app does suggest a list of movie names that are in my collection but it’s always a “No results” when I select one.

**Comment by bmdelaune** [comment] 2023-01-02 23:38
I'm having the same issue as well. tvOS and iOS both

**Comment by Jeffersonian** [comment] 2023-01-06 03:21
Same issue.  Movies don’t show, but I can find one if I search or if I add a genre filter.

**Comment by daytooth** [comment] 2023-01-07 19:30
Same issue here in relation to no movies showing on tvOS
Application version
1.0.0(84)

Where did you install the app from?
App Store

Device information
Apple TV 2017 A1842

OS version
tvOS 12.2 (20K362)

Jellyfin server version
10.8.8

**Comment by JaseSmith78** [comment] 2023-01-09 04:23
Same issue here in relation to no movies showing on tvOS
Application version
1.0.0(84)

Where did you install the app from?
App Store

Device information
Apple TV 4k A2169

OS version
tvOS 16.2 (20K362)

Jellyfin server version
10.8.8

**Comment by tsfoni** [comment] 2023-01-11 08:20
Same on iPad and iPhone, no movies.

**Comment by RobertClum** [comment] 2023-01-12 03:40
I'm having the same issues as well. 

Movies don't show up, just the last played, but won't play if clicked on.

TV Shows I'm seeing listed, but no episodes play. Turned on force direct play didn't help.

One thing that worked is I have some older mp4 fitness videos from probably 15 years ago, which play without issue. No clue why. I moved a movie file to this same directory to see if it would play and then all the videos stopped working including the old ones which use to work. I removed the newer movie and the old videos started working again.

All videos are MP4


Application version
1.0.0(84)

Where did you install the app from?
App Store

Device information
Apple TV 4k A1842

OS version
tvOS 16.2 (20K362)

Jellyfin server version
10.8.8 (Docker)

**Comment by nlflint** [comment] 2023-01-25 05:12
The original bug is two separate issues: No Movies, and M4V won't play.

The "No movies" bug is a duplicate of #621.

As for M4V not playing, more info is needed about the video. I have some M4V's that play while others do not. Anyone know how to get AppleTV app logs?

**Comment by ArkadyMel** [comment] 2023-03-07 03:18
I have this issue with movies not displaying, I suspect there is a threshold where if a certain number is exceed it won't display any results. I set up a much smaller library with only a dozen or so movies and it works fine. My main library has more than 100 movies and it just says "No Results". Interestingly I can play any movie, it seems to find any title I search for but have to sometimes put quite a lot of the title in the search.

**Closed** 2023-03-12 09:00 UTC
Labels: bug
