### ISSUE TITLE
No media found

### ISSUE THREAD

**Issue by ghost** [jellyfin/Swiftfin#712] opened 2023-02-28 22:21 UTC
### Describe the bug

Once connected the app shows no media at all. Other apps that connect to the same server work just fine. This includes Finamp and Jellyfin for iOS. 

### Application version

1.0.0(79)

### Where did you install the app from?

App Store

### Device information

iPhone 13 mini

### OS version

iOS 16.3.1

### Jellyfin server version

10.8.9

**Comment by Shevalier4444** [comment] 2023-03-01 12:56
I have the same problem

**Comment by MLIUKF** [comment] 2023-03-04 14:25
Same🤷🏼‍♂️

**Comment by lousmet** [comment] 2023-03-05 18:28
I have the same issue on TV Os, seems to be related to Swiftfin. I found this interesting link on reddit which describes my problem well, unfortunately I am not able to find my logs to confirm. 

https://www.reddit.com/r/jellyfin/comments/106jzhe/swiftfin_apple_tvos_app_doesnt_work/

CO47246:"I used to have this issue. What it ended up being for me is that some movies/episodes had bad JSON for their Jellyfin records in the database. To resolve this, I removed the file from the directory and readded it.

The biggest difference for me is that the issue start occurring after I added a specific movie so it was easy for me to identify the root cause movie to resolve this. To confirm if you are seeing the same JSON issue, you can download the Swiftfin on an iPhone or iPad and try to load the same libraries. If it's JSON related, it should do the same thing and not load. However, you can then go to the Files app on iPhone or iPad and there is a folder for Swiftfin where the logs go. There, you can check to validate if it's a JSON parsing issue."

**Comment by davetunnicliff** [comment] 2023-03-05 20:46
Dupe of #621

**Closed** 2023-03-05 21:27 UTC
Labels: bug
