### ISSUE TITLE
Can’t read local subtitles and decode ability for 4K is weak

### ISSUE THREAD

**Issue by Yumega** [jellyfin/Swiftfin#506] opened 2022-07-30 14:20 UTC
1, can’t read local subtitles, infuse can, but infuse ui looks bad

2, can’t smoothly decode 2016P SDR, infuse can decode smoothly 

Application version

1.0.0(76)

Where did you install the app from?

TestFlight

Device information

Appletv 4k 2021

OS version

tvOS 15

Jellyfin server version

10.8.1

**Comment by LePips** [comment] 2022-08-03 22:18
Subtitles not being displayed is a duplicate of https://github.com/jellyfin/Swiftfin/issues/417. Sadly, we don't control any video playback due to depending on VLCKit so there's nothing we can do about it. Anecdotally, I can watch 4k video just fine on the same hardware.

**Closed by LePips** 2022-08-03 22:18 UTC
