### ISSUE TITLE
iPad OS bar on the bottom doesn't hide after playing a video

### ISSUE THREAD

**Issue by vallezw** [jellyfin/Swiftfin#836] opened 2023-09-07 14:58 UTC
### Describe the bug

I have an iPad 4th gen and if I play any kind of video the bar on the bottom doesn't hide. When looking at youtube e.g. the bar hides after watching 1 second. I don't know if this is easily fixable, but if so please fix it, since it is a bit irritating.

See my screenshots below as an example:

**Example Swiftin**:
4:3
![display_1](https://github.com/jellyfin/Swiftfin/assets/50796600/1f657982-a825-4a86-8989-ed5b4f6fc60a)
16:9
![photo_2023-09-07_16-55-21](https://github.com/jellyfin/Swiftfin/assets/50796600/9c423d45-b350-471c-8b90-b3f8c66c6423)

**Example Youtube**:
![display_youtube](https://github.com/jellyfin/Swiftfin/assets/50796600/a9ed7079-b34d-43f1-bc9f-72b93606f468)

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPad Air (4th generation)

### OS version

iPadOS 16.6

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment] 2023-09-07 19:02
Duplicate of #582

**Closed by thornbill** 2023-09-07 19:02 UTC
Labels: bug, duplicate
