### ISSUE TITLE
Backdrop not scrolling with content foreground

### ISSUE THREAD

**Issue by krejcar25** [jellyfin/Swiftfin#1180] opened 2024-08-11 19:39 UTC
### Describe the bug

1. Open a Collection, Movie or a Show.
2. See that content backdrop is aligned correctly with bottom edge of blur.
<details>
<summary>Before Screenshots</summary>

![iPad Collection Landscape Before](https://github.com/user-attachments/assets/2065b1fc-90a5-4c7c-8335-22fa9a86cac8)
![iPad Movie Landscape Before](https://github.com/user-attachments/assets/08dd1891-3fa8-41f0-9935-0a8cb9da817c)
![iPad Movie Portrait Before](https://github.com/user-attachments/assets/a8017871-7327-4d58-9436-95840778aa1e)
![iPhone Movie Portrait Before](https://github.com/user-attachments/assets/621565aa-e062-42be-83bb-22f735342109)
</details>

3. Scroll some.
4. Try and fail to read text in foreground with backdrop fixed in original place.
<details><summary>After Screenshots</summary>

![iPad Collection Landscape After](https://github.com/user-attachments/assets/2e086799-278a-4d37-9054-2295d369e455)
![iPad Movie Landscape After](https://github.com/user-attachments/assets/ffdcc2b0-e701-47c7-b967-b1cb12a5bb67)
![iPad Movie Portrait](https://github.com/user-attachments/assets/9fc549a4-d6bb-4d15-b7a5-977cc57bc6f4)
![iPhone Movie Portrait After](https://github.com/user-attachments/assets/9d0fad10-9ddb-4859-b583-b621c46f10d1)
</details>

### Application version

1.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 15 Pro, iPad Air (5th generation)

### OS version

iOS 18.0 beta (22A5326f), iPadOS 18.0 beta (22A5326f)

### Jellyfin server version

10.9.6

**Comment by oxixes** [comment] 2024-08-13 01:59
Duplicate of #1121 and fixed by #1135 (not yet published).

**Closed** 2024-08-13 02:49 UTC
Labels: bug
