### ISSUE TITLE
"All Media" does not show all media in library by default

### ISSUE THREAD

**Issue by krutburken** [jellyfin/Swiftfin#236] opened 2021-11-25 08:14 UTC
### Describe the bug

1. Tap on All Media, then Movies (in my case)
2. The list shown will by default only contain 10 items and no further pages. Not sure why this number in particular. I've tried on several devices and it's the same regardless.
3. Go into the filter options and manually enable all Genres, Apply filter.
4. List is now fully populated.

When leaving this page and going back, the filter is reset and page again only contains 10 items.

### Application version

1.0.0 (66)

### Where did you install the app from?

TestFlight

### Device information

iPhone 12 mini

### OS version

15.1.1

### Jellyfin server version

10.7.7

**Comment by PangMo5** [comment] 2021-11-25 08:25
Please let me know the folder structure of the library.

**Comment by krutburken** [comment] 2021-11-25 08:40
Hi! 
It's a Movie library with about 1800 Movies. There are no problems in other clients, and Jellyfin has no problem identifying new items.

Structure (handled by radarr):
`<filesystem>/Movies/Movie.Name_2021/Movie.Name.2021.1080p.WEB.H264-NOGRP/movie.name.2021.[tmdbid-99999].ext`

**Comment by PangMo5** [comment] 2021-11-25 08:51
Oh, thank you.
Maybe it's because there are video files in more than one recursive folder.

_for development_
Currently, there is a logic in `LibraryViewModel` that send `recursive ` to `false` when calling `ItemsAPI.getItemsByUserId`.
it will work normally if it is sent to `true`.
It would be nice to know for what reason the logic has been created.

**Comment by LePips** [comment] 2021-11-25 17:55
Duplicate of https://github.com/jellyfin/Swiftfin/issues/175

**Comment by LePips** [comment] 2021-11-25 17:55
But won't close cause this is a big issue and I guess having more issues of the same type will show how pressing it is

**Closed** 2022-01-03 18:57 UTC
Labels: bug, duplicate
