### ISSUE TITLE
Gesture bar not going away on oficial IOS APP

### ISSUE THREAD

**Issue by ppmanu3223** [jellyfin/Swiftfin#655] opened 2022-12-30 10:49 UTC
### Describe the bug

Gesture bar not going away on oficial IOS APP

### Application version

1.0.0

### Where did you install the app from?

App Store

### Device information

iPhone 13 pro

### OS version

iOS 16.2

### Jellyfin server version

10.8.8

**Comment by oxixes** [comment] 2022-12-30 12:33
Duplicate of #582

**Closed** 2022-12-30 15:14 UTC
Labels: bug
