### ISSUE TITLE
Autorotate, when leaving the video player, does not work on iPhone. 

### ISSUE THREAD

**Issue by Scorpionhunt** [jellyfin/Swiftfin#763] opened 2023-05-03 09:40 UTC
### Describe the bug

1. Play any content (h.264 or h.265) by pressing the play button (while the phone is in portrait mode)
2. Player starts playing and automatically rotates to landscape mode.
3. Exit the player by tapping the back button in the upper left corner.
4. Swiftfin exits the player but stays in horizontal mode instead of rotating back to portrait mode. The phone itself is in a portrait position. 
5. Rotation is only possible in landscape mode but not in portrait mode.

To solve this issue:
1. Tap on the back button in the upper left corner to get to the home screen - the app automatically rotates into portrait mode.
2. Close the app completely. The phone, as well as the app, will switch to portrait mode again .

I do not have this problem on my iPad. 

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 12

### OS version

16.4.1

### Jellyfin server version

10.8.10

**Comment by LePips** [comment] 2023-05-04 20:28
Duplicate of #384

**Closed by LePips** 2023-05-04 20:28 UTC
Labels: bug
