### ISSUE TITLE
INVITATION CODE TESTFLIGHT

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#829] opened 2023-08-27 18:35 UTC
HELLO

i would like to know how to get testflight swiftfin version 2023-08-22
The last version I have that no longer works dates from 2023-06-19

is there a new test session. can I participate ?

Is there an invitation code? please

**Comment by thornbill** [comment] 2023-08-28 01:44
Duplicate of #753 and many others

**Closed by thornbill** 2023-08-28 01:44 UTC
Labels: enhancement

**Comment by Fletcher-Alderton** [comment] 2023-09-23 11:19
Hey I know you guys probably get a lot of people asking but when is the TestFlight going to open again as there hasn’t been an official update to the app in 6 months and you guys continue to mark issue as fixed yet only a handful of people can experience the fixed version and it’s quite infuriating. Thanks

**Comment by G10vanni74** [comment] 2023-09-23 11:24
> Hey I know you guys probably get a lot of people asking but when is the TestFlight going to open again as there hasn’t been an official update to the app in 6 months and you guys continue to mark issue as fixed yet only a handful of people can experience the fixed version and it’s quite infuriating. Thanks

I agree with you    It s very long without news
