### ISSUE TITLE
The "Home Button (Line)" does not hide when playing content on iPhone 12 or iPad Pro.

### ISSUE THREAD

**Issue by Scorpionhunt** [jellyfin/Swiftfin#764] opened 2023-05-03 10:01 UTC
### Describe the bug

1. Play any content (h.264 or h.265) by pressing the play button.
2. The "Home Button (Line)" does not hide after several minutes of playback. 

This issue occurs on iPad Pro (2020) and iPhone 12, as well as on iPad 7, all running the latest IOS and Swiftfin versions.

Thank you for your help. 

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 12, iPad Pro (4th generation)

### OS version

16.4.1

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment] 2023-05-03 12:08
This is a duplicate of #582.

**Closed** 2023-05-03 12:08 UTC
Labels: bug, duplicate

**Comment by Scorpionhunt** [comment] 2023-05-03 18:42
Sorry, I scrolled through the issues but missed it.
