### ISSUE TITLE
Taking on home buttons should navigate to the top-level page (iOS)

### ISSUE THREAD

**Issue by andromidasj** [jellyfin/Swiftfin#372] opened 2022-02-08 14:06 UTC
The two navigation buttons at the bottom: Home and All Media. When browsing media and getting a few levels deep (e.g. Home > select a movie > select an actor > select another movie from the actor > select a genre), tapping on Home should take us back to the top level Home page instead of needing to hit Back a few times.

This could also call for support for back _and_ forward swiping to navigate back and forth, but that might be better as its own request(?).

**Comment by LePips** [comment] 2022-02-08 14:12
Duplicate of https://github.com/jellyfin/Swiftfin/issues/209. We can't don't anything about this on our own and have to wait for SwiftUI to mature.

**Closed** 2022-02-08 14:12 UTC
Labels: duplicate
