### ISSUE TITLE
Local EPG - create local channels for moview/series genres that play a playlist

### ISSUE THREAD

**Issue by shadzik** [jellyfin/Swiftfin#735] opened 2023-03-22 16:13 UTC
Hey,

I'm working on an EPG feature, that basically creates some random (currently not yet random) channels with specific movie genres.
So I get let's say 10 action movies, an EPG is created and I can select a movie from that EPG channel. Please see the attached video.

**Additional context**

https://user-images.githubusercontent.com/2404568/226968051-5e9ba7c3-4ea7-4d2f-abe4-bd42d171b288.mov

My question is: how  can I create a playlist out of an [BaseItemDto] array, so that when a movie finishes playing, the next one starts automatically, giving you the illusion of having a channel on that plays the next movie from the guide.

Thanks for your help!

**Comment by LePips** [comment] 2023-03-22 19:05
I am excited for a proper EPG view! For this request specifically (playlists) I want to mark as duplicate of #609. I have only briefly thought about a playlist/queue implementation but I expect a lot of quirks will need to be figured out once I get there.

**Closed as completed by LePips** 2023-03-22 19:05 UTC
Labels: enhancement

**Comment by shadzik** [comment] 2023-03-22 22:35
@LePips I've seen somewhere in the code the possibility to create playlists - probably for the backend Jellyfin server, right? I was wondering if that could be used to get it working. I haven't seen a ViewModel that would support multiple BaseItemDto's... My question is now, how to procede... as I know VLC supports playlists (m3u and if i remember correctly some other ways of playing items sequentially) I could figure something out that works for me and my use case - it would be a little bit of pointless effort if that work would stay with me and I would have to always patch it on top of upstream. Do you have a milestone path that you're following for features etc. or is it more or less all in your vision?

**Comment by LePips** [comment] 2023-03-23 00:27
Swiftfin has nowhere to create or deal with playlists and you are correct, no view model's have anything to use playlists because it isn't implemented yet. While VLC can support playlist file formats, we do not use VLC in that way. All we give to the VLC layer is a stream to play and Swiftfin handles all media ordering and play requests.

My only "path" is "whenever I can get to it", so I cannot promise anything.

As a small request, please do not ping my name as I am watching the repo and am notified of all comments made on it.

**Comment by shadzik** [comment] 2023-03-23 12:12
Thanks for your answer! I've solved my problem using the `nextItemVideoPlayerViewModel` approach you've created for adjacent episodes. That way I have a kind of playlist feature, which is enough for my EPG. Thanks again!
