### ISSUE TITLE
Subtitles not displaying iOS

### ISSUE THREAD

**Issue by KillsT3aler69** [jellyfin/Swiftfin#1376] opened 2024-12-25 15:26 UTC
### Describe the bug

When pressing the button, I can see the available subtitles. But when I select one, the menu closes and the subtitles don't appear. When I go back to the menu it still displays it as unchosen. This issue is present with both embedded and external subtitles. Video player type is set to Swiftfin. The subtitles work fine on the web version (both on iPhone/Safari and PC) and on AndroidTV. Subtitles also don’t work on the Jellyfin iOS app.

### Application version

1.2

### Where did you install the app from?

None

### Device information

iPhone 15

### OS version

iOS 18.2 (22C152)

### Jellyfin server version

10.10.3

**Comment by JPKribs** [comment] 2024-12-25 16:20
Duplicate of https://github.com/jellyfin/Swiftfin/issues/1256

**Closed by JPKribs** 2024-12-25 16:20 UTC
Labels: bug
