### ISSUE TITLE
Airplay playback is missing

### ISSUE THREAD

**Issue by iwa** [jellyfin/Swiftfin#698] opened 2023-02-11 11:00 UTC
**Describe the feature you'd like**
When watching a video, it's not possible to airplay the content to an Apple TV or a Mac
When using the screen mirroring and launching a video, it keeps mirroring the screen instead of starting an Airplay video playback

**Additional context**
I can provide a little screen recording if needed

**Comment by LePips** [comment] 2023-02-11 22:10
VLCKit does not support Airplay, I will also consider this duplicate of #606

**Closed by LePips** 2023-02-11 22:10 UTC
Labels: enhancement

**Comment by iwa** [comment] 2023-02-12 21:04
that's strange because the official vlc ios app has the feature, so it should be possible to add it in a way, right?
