### ISSUE TITLE
My library does not update

### ISSUE THREAD

**Issue by GaetanPTX** [jellyfin/Swiftfin#849] opened 2023-09-18 17:54 UTC
### Describe the bug

My library does not update on its own, new added media do not appear

### Application version

1.0.0(74)

### Where did you install the app from?

App Store

### Device information

Apple TV 2e Gen

### OS version

tvOS 16.6

### Jellyfin server version

10.8.10

**Comment by Jpkribs** [comment] 2023-09-19 02:03
I believe this is a duplicate of https://github.com/jellyfin/Swiftfin/issues/619. If you restart the app the home page should refresh. I believe refreshing automatically when going to the home page is on the radar.

**Closed** 2023-09-21 18:12 UTC
Labels: bug
