### ISSUE TITLE
Scrolling fast within a library causes overlap and shifting

### ISSUE THREAD

**Issue by ericswpark** [jellyfin/Swiftfin#880] opened 2023-10-13 15:55 UTC
### Describe the bug

1. Click on a library with lots of items
2. Start scrolling down rapidly
3. The items that load in will overlap with the previous items' titles (see attached screenshot)

![Screenshot 2023-10-13 at 11 51 16 AM](https://github.com/jellyfin/Swiftfin/assets/13326074/8f95b2df-df2f-42b0-954f-08b018b54bff)

### Application version

043a95d

### Where did you install the app from?

Self-compiled

### Device information

iPhone 14 Pro Max

### OS version

iOS 17.0.3

### Jellyfin server version

10.8.11

**Comment by ericswpark** [comment] 2023-10-13 16:29
I'm guessing the bug is occurring due to the variable title length, so if we change the item to display the title in a single line and possibly the release year right beneath, then it can be fixed at 2 lines and there won't be shifting?

**Comment by extraslute** [comment] 2023-10-13 17:08
I can confirm that has been happening for two years now. Apple TV is where I see it.

**Comment by LePips** [comment] 2023-10-13 20:45
Considering this a duplicate of: #557, and you can see my comment on the behavior in #536.

**Closed by LePips** 2023-10-13 20:45 UTC
Labels: duplicate
