### ISSUE TITLE
Please add Quality/Transcoding settings to control buffering

### ISSUE THREAD

**Issue by teddyursa** [jellyfin/Swiftfin#791] opened 2023-06-15 22:38 UTC
**Describe the feature you'd like**
I'm on a server which struggles to play 1080p video which is really unfortunate. On the jellyfin PC app I can control the maximum speed / quality of the files and they work fine, but on Apple TV there's no such options so i'm stuck with buffering videos. Some things are fine, then others will buffer their butts off :(

Thanks, this would be amazing like the PC program.

**Comment by ericswpark** [comment] 2023-06-19 08:31
Duplicate of #184

**Closed** 2023-06-20 00:40 UTC
Labels: enhancement
