### ISSUE TITLE
Ability to select target bitrate 

### ISSUE THREAD

**Issue by Aljutor** [jellyfin/Swiftfin#769] opened 2023-05-09 00:29 UTC
**Describe the feature you'd like**
I would be nice to have some ability to force select target bitrate profile, similar to web version.

**Additional context**
In some instances swiftfin selects profile with too high bitrate for network to handle smoothly.

**Comment by LePips** [comment] 2023-05-15 22:11
Duplicate of #184

**Closed by LePips** 2023-05-15 22:11 UTC
Labels: enhancement
