### ISSUE TITLE
M1 iPad Pro - Latest testflight refuses to play any video

### ISSUE THREAD

**Issue by harryofbath** [jellyfin/Swiftfin#293] opened 2022-01-13 05:04 UTC
Updated from 67 to 68 and now videos no longer play. This is independent of encoding or container, and effects my entire library. I get a strange result in my log every time I go to play a video, seen below.

`2022-01-13 04:55:21.229 +00:00] [INF] [21] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 60000000, MaxStaticBitrate: 60000000, MusicStreamingTranscodingBitrate: 60000000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mov,mp4,mkv,webm", AudioCodec: "aac,mp3,wav,ac3,eac3,flac,truehd,dts,dca,opus", VideoCodec: "h264,hevc,dvhe,dvh1,h264,hevc,hev1,mpeg4,vp9", Type: Video }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "hevc,h264,mpeg4", AudioCodec: "aac,mp3,wav,ac3,eac3,flac,opus", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 2, SegmentLength: 0, BreakOnNonKeyFrames: True }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: Video, Conditions: [], ApplyConditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "80", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [], ApplyConditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|main 10", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "175", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "ass", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "pgssub", Method: Embed, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "subrip", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "sub", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] } `

On M1 iPad Pro, with Jellyfin on 10.8.0 alpha 5, however issue existed on 10.7.7. In the dashboard, it shows the video as actively playing, but paused, and reports it as direct playing. However the video never begins.

**Comment by LePips** [comment] 2022-01-13 05:09
We have to send a request to the server for the media streams for the item and we have to tell them what device we're using. I _think_ this may be because we don't have the M1 iPad Pro in our device list, but I also don't get why it broke from 67 to 68 if it wasn't there before. I don't have an M1 iPad Pro to test with. If I were able to try some things, would you be able to test on my branch/PR?

**Comment by harryofbath** [comment] 2022-01-13 05:22
I would be willing to test, but I don't have a Mac, which I assume I would need. If it works through TestFlight then sure.

**Comment by LePips** [comment] 2022-01-13 05:30
That should be okay then. A new build will be out soon with a bunch of small things, I'll make sure this gets in.

**Comment by hendrik1120** [comment] 2022-01-13 11:45
Hi, I was able to reproduce the exact same error message with TestFlight version 68 on my M1 MBP as it's also not listed in the Device Profile dictionary. But I am still able to playback all my content.
I rather think it's the same issue I experienced which now magically fixed itself.

@harryofbath Let me guess if you touch on the black screen after you pressed play, you can see the media controls e.g. progressbar, subtitles, etc. but nothing happens?

If thats the case the following steps might resolve the issue:
1. Delete the app and reinstall it from TestFlight again.
2. Restart your yellyfin server or if in docker: rebuild container.
3. Try again.

**Comment by harryofbath** [comment] 2022-01-13 15:32
@hendrik1120 Thanks for the suggestion. Unfortunately your fix did not work in my case.

**Comment by LePips** [comment] 2022-01-13 15:52
Along with putting the device profiles, transcoding was fixed also so I do expect this to be fixed then. However M1 should direct play everything, so I actually ask anyone with M1 devices to report whether streams are transcoded or direct play on the next build (after 68)

**Comment by hendrik1120** [comment] 2022-01-13 19:01
Yes, can confirm. Cinematic view prevents me from playing the file.

**Comment by LePips** [comment] 2022-01-13 19:09
Is the Play button grayed out at that moment?

**Comment by hendrik1120** [comment] 2022-01-13 19:11
Yes. But not on all mkv files.

**Comment by hendrik1120** [comment] 2022-01-13 19:24
Apparently playing the file on the testflight version makes the greyed out button go away and lets me playback the blackscreen again :D
Even after marking it as unplayed on the server.
Now I only got one show left with the grey button and it says:
 [🔴 ERROR] CinematicItemViewTopRow#65:body Attempted to play item but no playback information available

**Comment by LePips** [comment] 2022-01-13 19:41
First, the grayed out button and the logging error is the (new) expected behavior. This is because it doesn't have a stream to, well, stream from. Going one step back, this means that there aren't any media sources to play the item from.

By chance, does the specific media item have multiple version by chance? (1080p, 720p, etc.)

Notice, I'm not asking about _files_, I'm asking about _items_. The _item_ is telling us that it doesn't have a proper _file_ to create a stream from.

**Comment by LePips** [comment] 2022-01-13 19:43
This error has encouraged me to put _a lot_ more logging in.

**Comment by hendrik1120** [comment] 2022-01-13 20:03
I hope I understand correctly. There would be no way for the item to have multiple versions. It has only been indexed once by jellyfin and never been played or transcoded by jellyfin before. I also only have one resolution per movie. Either 1080p or 4k but never both at the same time. There are also no duplicates of any kind.

All my media is also encoded in the same way. All underlying files have H.265 and the video in the first stream.

Yes, more logging would be really great because you will have all kinds of media being played by the app.

**Comment by hendrik1120** [comment] 2022-01-13 20:21
I found a way to toggle the grey button. If I mark the whole series as played in the web interface it turns grey which should mean that it cant get a stream. If I mark it as unplayed it turns normal again XD. It makes no sense at all.
But playback still doesnt work.

**Comment by LePips** [comment] 2022-01-13 20:46
Oh, is it a series you're trying to play from? Not the episode page?

If so, this is (currently) expected as the correct logic for getting the "Next Up" item in a series isn't complete.

**Comment by hendrik1120** [comment] 2022-01-13 20:59
Ok, the grey button ofc only appears on the show in: top slider -> tvShows -> Game of Thrones for example.

The following ways show the regular play button with time stamp in it.
top slider -> home -> first row -> Game of Thrones (with the big wp)
top slider -> home -> second row -> play next -> Game of Thrones
top slider -> home -> latest "series" -> GoT 

no matter which button I press its still the same black screen.

I also found this probably related issue [https://github.com/jellyfin/jellyfin/issues/3815](url) that might help.

**Comment by LePips** [comment] 2022-01-13 21:46
The gray button isn't currently the problem, that behavior will be polished over time and not something I'm worried about at the moment.

To relate to the current issue and the "black screen when playing", what Apple TV Hardware are you using? This may be a transcoding issue which relates to the original issue, and transcoding was fixed however the Apple TV you are using may not be constructing the device profile correctly since you mention this is all H.265 content.

If so, this problem extends more than I thought with per-device support and actually may not be addressable in the next build.

**Comment by harryofbath** [comment] 2022-01-15 00:22
Got version 69 today, and no change. Device still reported as null and videos do not play.

**Comment by LePips** [comment] 2022-01-17 16:33
This may be fixed thanks to https://github.com/jellyfin/Swiftfin/pull/309, test in next build (after 69)

**Comment by LePips** [comment] 2022-01-20 21:38
The new TestFlight was released, please test this and report back whether playback is fixed.

**Comment by harryofbath** [comment] 2022-01-21 07:07
> The new TestFlight was released, please test this and report back whether playback is fixed.

Yes! Everything plays! Thank you so much. Chapter selecting also works well.

**Closed** 2022-01-21 07:08 UTC
Labels: bug

**Comment by LePips** [comment] 2022-01-21 07:46
Chapters only show if they have chapters that the server recognizes, not from the media

**Comment by harryofbath** [comment] 2022-01-21 08:45
For the episodes where I cannot select chapters, they appear at the bottom of the webUI where you would expect them, however the chapters button within Swiftfin is not listed for them during playback.

**Comment by harryofbath** [comment] 2022-01-21 08:52
Upon further inspection, it seems that it is merely inconsistent on whether chapters should be accessible or not. I can load an episode, and see chapters, then load a different episode, no chapters, go back to the first episode, chapters gone.
