### ISSUE TITLE
Audio file playback

### ISSUE THREAD

**Issue by scientificCommunity** [jellyfin/Swiftfin#822] opened 2023-08-12 04:27 UTC
**Describe the feature you'd like**

hi !  I didn't find a music playback portal like on the jellyfin-web,  Did I set it up incorrectly somewhere, or does it not have this feature itself?  If not, Do you have any plans to support music like .mp3 file playback?  

**Additional context**

**Comment by LePips** [comment] 2023-08-12 07:42
Duplicate of so many, just linking #6.

**Closed by LePips** 2023-08-12 07:42 UTC
Labels: enhancement
