### ISSUE TITLE
airplay support, subtitle setting

### ISSUE THREAD

**Issue by Simoooon** [jellyfin/Swiftfin#531] opened 2022-08-19 02:49 UTC
Hi, guys. I've been using Jellyfin server and Swiftfin for a few days. It's so amazing, I really appreciate your time and effort.
I also ran into a few issues:

1. I could not play audio on my Speaker via airplay, audio track was AAC encoded.. does Swiftfin support airplay? 

2. It doesn't remember subtitle settings. By default, subtitle is enabled. I prefer to watch shows without subtitle, but I have to turn off subtitle every time a new episode begins. I think it should remember user's choice. If user turn it off, it should remain off util user turn it back on.

3. Recently add and Latest movies are the same..
![Screen Shot 2022-08-18 at 8 58 06 PM](https://user-images.githubusercontent.com/14824945/185529751-d6b19a5f-7029-45a6-be0f-aa98f0ce1d33.jpg)
I personally think that Latest movies should be movies recently released not movies recently added to the library. Anyway, it doesn't matter how you interpret it. Having two identical sections on Home screen seems a bit redundant.

4. When movies are grouped into collections. It has "S0:E0" under the poster.
![Screen Shot 2022-08-18 at 8 59 59 PM](https://user-images.githubusercontent.com/14824945/185531184-36294ff4-55ee-4023-912f-9f3c9ab5a7de.jpg)

5. Could you add a refresh button on Home Screen ? 
every time I add movies to the library, I have to restart Swiftfin to see the changes, a refresh button would make it a lot easier.

My device: Apple TV 4K 2nd Gen running tvOS 15.6
Server version: Jellyfin 10.8.3
Swiftfin version: 1.0.0 (79)

Thank you very much for your time and consideration.

**Comment by LePips** [comment] 2022-08-19 03:13
1 - VLCKit does not accurately support Airplay, nothing we can do about it.
2 - If a subtitle track was chosen on the media from the server, we set the subtitle track
3 - Duplicate of https://github.com/jellyfin/Swiftfin/issues/203. It just so happens that your recently added media are movies but yes this will change
4 - These views will be redone
5 - There technically is one but it can be hard to navigate to as it was just for my development purposes. It was removed for now (but is still there in the current release) and a new method for refreshing will be added

**Closed by LePips** 2022-08-19 03:13 UTC
Labels: enhancement

**Comment by extraslute** [comment] 2022-08-19 10:00
> Hi, guys. I've been using Jellyfin server and Swiftfin for a few days. It's so amazing, I really appreciate your time and effort.
> 
> I also ran into a few issues:
> 
> 
> 
> 1. I could not play audio on my Speaker via airplay, audio track was AAC encoded.. does Swiftfin support airplay? 
> 
> 
> 
> 2. It doesn't remember subtitle settings. By default, subtitle is enabled. I prefer to watch shows without subtitle, but I have to turn off subtitle every time a new episode begins. I think it should remember user's choice. If user turn it off, it should remain off util user turn it back on.
> 
> 
> 
> 3. Recently add and Latest movies are the same..
> 
> ![Screen Shot 2022-08-18 at 8 58 06 PM](https://user-images.githubusercontent.com/14824945/185529751-d6b19a5f-7029-45a6-be0f-aa98f0ce1d33.jpg)
> 
> I personally think that Latest movies should be movies recently released not movies recently added to the library. Anyway, it doesn't matter how you interpret it. Having two identical sections on Home screen seems a bit redundant.
> 
> 
> 
> 4. When movies are grouped into collections. It has "S0:E0" under the poster.
> 
> ![Screen Shot 2022-08-18 at 8 59 59 PM](https://user-images.githubusercontent.com/14824945/185531184-36294ff4-55ee-4023-912f-9f3c9ab5a7de.jpg)
> 
> 
> 
> 5. Could you add a refresh button on Home Screen ? 
> 
> every time I add movies to the library, I have to restart Swiftfin to see the changes, a refresh button would make it a lot easier.
> 
> 
> 
> My device: Apple TV 4K 2nd Gen running tvOS 15.6
> 
> Server version: Jellyfin 10.8.3
> 
> Swiftfin version: 1.0.0 (79)
> 
> 
> 
> Thank you very much for your time and consideration.
> 
> 



I can second that we have an annoyance with the subtitles being enabled by default as well. When you watch Netflix or Hulu or anything else, subtitles are an option but are disabled unless turned on. Mine and my other half's preference is that they be disabled unless I want them on for a specific show. Not enabled on everything by default.
