### ISSUE TITLE
No HDR or DV

### ISSUE THREAD

**Issue by Scoty43** [jellyfin/Swiftfin#761] opened 2023-04-28 12:46 UTC
I use the latest Apple TV 4K 2022 and Video with HDR or DV dont play, only SDR. Native Player not work, when enable no Video play.

Swiftfin 1.0.1 (70)
tvos 16.4.1

**Comment by holow29** [comment] 2023-04-29 16:26
Native player is currently required for HDR because VLCKit does not support HDR at the moment. https://github.com/jellyfin/Swiftfin/pull/519 should fix some issues with native player.

**Comment by LePips** [comment] 2023-05-15 22:13
As said, VLCKit does not support HDR. 

Duplicate of #375

**Closed by LePips** 2023-05-15 22:13 UTC
