### ISSUE TITLE
Next Update 

### ISSUE THREAD

**Issue by G10vanni74** [jellyfin/Swiftfin#651] opened 2022-12-23 13:58 UTC
Impossible to refresh the contents read in the home page

1. is it planned to put a refresh button back

and 
2. will the correction be possible to make the thumbnail backdrops different as Ethan did some updates earlier?

thank you

**Comment by LePips** [comment] 2022-12-25 04:46
1 - duplicate of https://github.com/jellyfin/Swiftfin/issues/619
2 - duplicate of https://github.com/jellyfin/Swiftfin/issues/615

**Closed by LePips** 2022-12-25 04:46 UTC
