### ISSUE TITLE
white bar at bottom of screen will not go away 

### ISSUE THREAD

**Issue by iakeehc** [jellyfin/Swiftfin#795] opened 2023-06-18 15:18 UTC
### Describe the bug

when playing a video the white bar at the bottom of the screen will not go away even after waiting or not touching the phone on swiftfin

### Application version

1.0.1(78)

### Where did you install the app from?

App Store

### Device information

iphone 11

### OS version

16.5

### Jellyfin server version

10.8.10

**Comment by Jpkribs** [comment] 2023-06-18 15:27
This is a duplicate of: https://github.com/jellyfin/Swiftfin/issues/582

It has been resolved in the Main Branch and should be included in a future release.

**Closed** 2023-06-18 16:06 UTC
Labels: bug

**Comment by zeroquinc** [comment] 2023-09-19 07:23
When is this future release? 3 months after this post and I still have that bar :( For me it's unusable because of this.
