### ISSUE TITLE
Homebar stays on screen during playback

### ISSUE THREAD

**Issue by Glitch-Codes** [jellyfin/Swiftfin#744] opened 2023-04-10 01:40 UTC
### Describe the bug

During playback the "Homebar" on devices without a Home Button stays on screen and does not fade away. To replicate, play any media with anything iPhone X and up (besides the SE). This has been reported to be an eye sore and concern for OLED screens (even though these days burn in has many midigations). See image below for an example:

![unnamed](https://user-images.githubusercontent.com/54895281/230808632-f0f5ad90-fdc9-4597-89a3-3ddeb6f076e1.png)

### Application version

1.0.1 (78)

### Where did you install the app from?

App Store

### Device information

iPhone 13 Pro

### OS version

iOS 16.3

### Jellyfin server version

10.8.9

**Comment by QiuYueBaiJXW** [comment] 2023-04-14 12:51
Yes, and sometimes the subtitle is at the bottom of the screen, which exactly covered by the bar.

**Comment by QuanTrieuPCYT** [comment] 2023-04-15 16:31
Experiencing this too, I had to switch back to the old app due to this.

**Comment by Glitch-Codes** [comment] 2023-04-15 18:58
> Experiencing this too, I had to switch back to the old app due to this.

I did as well. Don't have access to a Mac or else I'd fix it. Going to see if I can get a VM going to at least bring forth a solution for others devs with access to a proper Xcode enviroment

**Comment by thornbill** [comment] 2023-04-15 19:20
Duplicate of #582

**Closed** 2023-04-15 19:21 UTC
Labels: bug, duplicate
