### ISSUE TITLE
macOS (Apple Silicon) app

### ISSUE THREAD

**Issue by nimalouk** [jellyfin/Swiftfin#1104] opened 2024-06-12 18:54 UTC
Any way you could add macOS as a target so I could install it in the App Store as an iPad app?

**Comment by thornbill** [comment] 2024-06-12 22:34
Duplicate of https://github.com/jellyfin/Swiftfin/issues/965

Please search for existing issues before creating a new one.

**Closed by thornbill** 2024-06-12 22:35 UTC
Labels: enhancement
