### ISSUE TITLE
Play on Device support

### ISSUE THREAD

**Issue by math-boy11** [jellyfin/Swiftfin#1299] opened 2024-10-31 16:29 UTC
**Describe the feature you'd like**

In the Jellyfin web/mobile client, there is an option to play the movie on another device that's also running Jellyfin. Essentially turning the device into a remote control. Is this feature possible/planned to add?

**Additional context**

Jellyfin v10.10.0
Swiftfin v1.2

**Comment by LePips** [comment] 2024-10-31 17:30
Considering duplicate of #408

**Closed by LePips** 2024-10-31 17:30 UTC
Labels: enhancement
